name: Horusec Security Scan

on: [push]

jobs:
  horusec-security-scan:
    runs-on: ubuntu-latest
    name: Run Horusec Security Scan
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Horusec Security Scan
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./
